version: "3.8"
services:
  weaviate:
    image: semitechnologies/weaviate:1.25.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - 50051:50051
      - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./data"
      PERSISTENCE_DATA_INDEXES_PATH: "./indexes"
      PERSISTENCE_DATA_SCHEMA_PATH: "./schema"
    networks:
      - weaviate

  nginx:
    image: nginx:latest
    ports:
      - 50052:50052
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - weaviate
    restart: on-failure:0
    networks:
      - weaviate

  knowledge-store:
    image: kstore:0.0.2
    ports:
      - 50053:50053
    depends_on:
      - weaviate
      - nginx
    environment:
      - GRPC_PORT=50053
      - GRPC_MAX_WORKERS=50
      - WEAVIATE_HOST=nginx
      - WEAVIATE_PORT=80
      - WEAVIATE_GRPC_PORT=50052
      - WEAVIATE_INDEX_NAME=DocumentIndex
      - WEAVIATE_TEXT_KEY=text
    networks:
      - weaviate

networks:
  weaviate:
